version: '3'

services:
  app:
    image: 'tdc-integracao-api:latest'
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: tdc-integracao-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ../../fabric/organizations/peerOrganizations/tdc.teste.com.br/users/User1tdc.teste.com.br/msp/:/etc/hyperledger/fabric/msp
      - ../core/etc/connection.yaml:/etc/connection.yaml
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - backend_teste

networks:
  backend_teste:
    external: true